services:
  app:
    build: .
    container_name: "app"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    # Кода из сборки – без bind mount

  beat:
    build: .
    container_name: "beat"
    command: uvicorn celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis
      - rabbitmq
    # Без volumes – используется собранный образ

  worker:
    build: .
    container_name: "worker"
    command: uvicorn celery -A app.celery_app worker -P asyncio --loglevel=info
    depends_on:
      - redis
      - rabbitmq
    # Без volumes

  db:
    image: postgres:15
    container_name: "postgres"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672" # AMQP порт
      - "15672:15672" # Management UI
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  alembic:
    build: .
    container_name: "alembic"
    command: uvicorn alembic upgrade head
    env_file:
      - .env
    depends_on:
      - db
    restart: "on-failure"

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
