version: '3.8'

services:

  app:
    build: .
    container_name: "app"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    ports:
      - "8000:8000"  # Открываем порт для доступа к приложению
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - YANDEX_TOKEN=${YANDEX_TOKEN}
    depends_on:
      - redis

  beat:
    build: .
    container_name: "music_sync_beat"
    command: celery -A app.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    container_name: "music_sync_worker"
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"  # Используем легковесный образ Redis
    ports:
      - "6379:6379"  # Открываем порт Redis

#  db:
#    image: "postgres:15-alpine"
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#
#  alembic:
#    build: .
#    container_name: "alembic"
#    command: alembic upgrade head
#    volumes:
#      - .:/app
#    environment:
#      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#    depends_on:
#      - db
#
#volumes:
#  postgres_data:
