"""create user

Revision ID: 94e08c7ed930
Revises:
Create Date: 2025-04-16 15:20:19.499331

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "94e08c7ed930"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
